### ISSUE TITLE
Surviving Mars zstd compression

### ISSUE THREAD

**Issue by mk-fg** [nickelc/hpk#11]
Hi,

Thanks a lot for your work on the tool and especially putting format details into README, saved me a bunch of time figuring it out from the code.

I've noticed that mods uploaded to Steam Workshop via Surviving Mars Mod Editor are packed into .hpk, which can be extracted by the tool, but unpacked files are still compressed with ZSTD signature at the start.

Which are same fragmented files as lz4/zlib-compressed ones, just using [zstd](http://facebook.github.io/zstd/) instead of these two.

Decompression script example:
https://github.com/mk-fg/games/blob/master/surviving-mars/zstd-dec.py#L39-L64

Not sure if it's also the case for other compression, but had to add "len(buff) != dst_len" check there as for e.g. .png files, despite ZSTD header, fragments are not compressed.

Attached ModContent.hpk.zip has ModContent.hpk for my simple mod, which has .lua and .png files with ZSTD header in it, both should be decompressible by python script above, but not currently handled by hpk tool itself, unfortunately.

[ModContent.hpk.zip](https://github.com/nickelc/hpk/files/2492531/ModContent.hpk.zip)

**Comment by nickelc** [comment]
Thanks for the info and the example hpk. I will look into it.

After digging through the C# code of the [Hpk Archiver](https://www.techpowerup.com/forums/threads/tropico-3-4-5-hpk-archiver.113705/) i thought it was important to write down all the information for the next guy.

**Comment by nickelc** [comment]
> Not sure if it's also the case for other compression, but had to add "len(buff) != dst_len" check there as for e.g. .png files, despite ZSTD header, fragments are not compressed.

if i recall it correctly this case should be catched when the [decoder fails](https://github.com/nickelc/hpk/blob/master/src/hpk/mod.rs#L329) to decompress a chunk.

**Comment by nickelc** [comment]
b187192 adds support for zstd compressed data but Appveyor fails for some reason.

**Comment by mk-fg** [comment]
Thanks again.

Looking through diff, noticed that you didn't seem to document it in the README.
Which to be fair I dunno if worth it, given that it only seem to be used in one very specific place atm.

Only used the tool with windows build, as Surviving Mars doesn't work on linux for me (crashes with open drivers which don't provide full OpenGL 4.5), so I'll try to test it once change makes it into some release tag.

**Comment by mk-fg** [comment]
> once change makes it into some release tag.

Which I guess 0.3.2 should've done if AppVeyor wasn't failing :)

Weird that it seem to say "Cancelled by the user" right now, though guess maybe it's due to some tinkering as you tried to make it work.

EDIT: ah, right, see bunch of build errors on previous attempt, apparently due to some mingw/rustc incompatibilities (rust-lang/rust#47048).

**Comment by nickelc** [comment]
It's an issue with the installed mingw version and the version used by rust internally.
I'll try using a stable mingw version instead of msys2.
If it's not working i'll disabled the *-pc-windows-gnu builds.

**Comment by nickelc** [comment]
*-pc-windows-gnu builds are fixed and [v0.3.2](https://github.com/nickelc/hpk/releases/tag/v0.3.2) is ready.

**Comment by mk-fg** [comment]
Thanks again for all the work, will be sure to report any issues.
