### ISSUE TITLE
FYI: For OSX, upgrade to zstd required

### ISSUE THREAD

**Issue by stephenfeather** [nickelc/hpk#12]
I had to modify the cargo for zstd to 4.22+zstd.1.3.8 to get it to build.

**Comment by nickelc** [comment]
thanks for the report. It's a good reason to setup travis for osx.
Would you like to post the build error?

**Comment by nickelc** [comment]
Ah, i see. it's not related to osx.
zstd 4.20+zstd.1.3.6 is pulling the incompatible dependency zstd-safe 1.4.7+zstd.1.3.8

**Comment by nickelc** [comment]
fixed with 854d8588f657c6ef3ff811ee9b426f7bbaa52235
