### ISSUE TITLE
Surviving mars corrupt extraction

### ISSUE THREAD

**Issue by ghost** [nickelc/hpk#9]
Trying to use this tool to extract the lua files from Surviving Mars, however the output file seems to be corrupted. Attached is one of the extracted lua files.

[TechTree.zip](https://github.com/nickelc/hpk/files/1825057/TechTree.zip)

**Comment by nickelc** [comment]
The extraction works correct. The lua files are compiled and contain only the lua 5.3 bytecode.

But it seems Haemimont Games made the bytecode header invalid so you have to edit the files with a hexeditor like [HxD](https://mh-nexus.de/en/hxd/) and add two missing bytes to make [luadec](https://github.com/viruscamp/luadec) or [unluac](https://sourceforge.net/projects/unluac/) work.
![hexview](https://www.techpowerup.com/forums/attachments/%E6%97%A0%E6%A0%87%E9%A2%98-png.98530/)

I gonna add an option to fix the bytecode headers for Surviving Mars but for now it's easier to edit the files manually.

**Comment by nickelc** [comment]
Duplicate of #8

**Comment by nickelc** [comment]
https://github.com/nickelc/hpk#game-scripting
